<?php if (!defined('FW')) die('Forbidden');

class FW_Option_Type_My_Icon extends FW_Option_Type
{
	/**
	 * Prevent enqueue same font style twice, in case it is used in multiple sets
	 * @var array
	 */
	private $enqueued_font_styles = array();

	public function get_type()
	{
		return 'my-icon';
	}

	/**
	 * @internal
	 */
	public function _get_backend_width_type()
	{
		return 'full';
	}

	/**
	 * @internal
	 * {@inheritdoc}
	 */
	protected function _enqueue_static($id, $option, $data)
	{
		wp_enqueue_style(
			'fw-option-type-'. $this->get_type() .'-backend',
			fw_get_template_customizations_directory_uri('/includes/option-types/'. $this->get_type() .'/static/css/backend.css'),
			fw()->manifest->get_version()
		);

		wp_enqueue_script(
			'fw-option-type-'. $this->get_type() .'-backend',
			fw_get_template_customizations_directory_uri('/includes/option-types/'. $this->get_type() .'/static/js/backend.js'),
			array('jquery', 'fw-events'),
			fw()->manifest->get_version()
		);

		$sets = $this->get_sets();

		if (isset($sets[ $option['set'] ])) {
			$set = $sets[ $option['set'] ];

			unset($sets);

			/**
			 * user hash as array key instead of src, because src can be a very long data-url string
			 */
			$style_hash = md5($set['font-style-src']);

			if (!isset($this->enqueued_font_styles[ $style_hash ])) {
				wp_enqueue_style(
					"fw-option-type-{$this->get_type()}-font-{$option['set']}",
					$set['font-style-src'],
					array(),
					fw()->manifest->get_version()
				);

				$this->enqueued_font_styles[ $style_hash ] = true;
			}
		}
	}

	/**
	 * @internal
	 */
	protected function _render($id, $option, $data)
	{
		$sets = $this->get_sets();

		if (isset($sets[ $option['set'] ])) {
			$set = $sets[ $option['set'] ];
		} else {
			$set = $this->generate_unknown_set($data['value']);
		}

		unset($sets);

		$option['attr']['value'] = (string)$data['value'];

		return fw_render_view(dirname(__FILE__) . '/view.php', compact('id', 'option', 'data', 'set'));
	}

	/**
	 * @internal
	 */
	protected function _get_value_from_input($option, $input_value)
	{
		$sets = $this->get_sets();

		if (isset($sets[ $option['set'] ])) {
			$set = $sets[ $option['set'] ];
		} else {
			$set = $this->generate_unknown_set($input_value);
		}

		unset($sets);

		if (is_null($input_value) || !isset($set['icons'][ $input_value ])) {
			$input_value = $option['value'];
		}

		return (string)$input_value;
	}

	/**
	 * @internal
	 */
	protected function _get_defaults()
	{
		return array(
			'value' => '',
			'set'   => 'ion-icons',
		);
	}

	private function get_sets()
	{
		$cache_key = 'fw_option_type_icon/sets';

		try {
			return FW_Cache::get($cache_key);
		} catch (FW_Cache_Not_Found_Exception $e) {
			$sets = apply_filters('fw_option_type_icon_sets', $this->get_default_sets());

			// do not allow overwrite default sets
			$sets = array_merge($sets, $this->get_default_sets());

			FW_Cache::set($cache_key, $sets);

			return $sets;
		}
	}

	private function generate_unknown_set($icon)
	{
		return array(
			'font-style-src'  => 'data:text/css;charset=utf-8;base64,LyoqLw==',
			'container-class' => '',
			'groups' => array(
				'unknown' => __('Unknown Set', 'fw'),
			),
			'icons' => array(
				$icon => array('group' => 'unknown'),
			),
		);
	}

	private function get_default_sets()
	{
		// FIXME Maybe its better to use something like the following:
		//
		//     groups => array(
		//         array(
		//             'title' => __('Web Application Icons', 'fw')
		//             'icons' => array('fa fa-adjust', 'fa fa-anchor', ...),
		//         ),
		//         array(
		//             'title' => __('Transportation Icons', 'fw'),
		//             'icons' => array(...),
		//         ),
		//     )
		//
		// NOTE Take into account backward compatibility

		return array(
			'ion-icons' => array( // http://fortawesome.github.io/Font-Awesome/icons
				'font-style-src' => get_template_directory_uri() . '/css/ionicons.css',
				'container-class' => '', // some fonts need special wrapper class to display properly
				'groups' => array(
					'all' => __('All Icons', 'fw'),
				),
				'icons' => array(
					'ion-alert' => array('group' => 'all'),
					'ion-alert-circled' => array('group' => 'all'),
					'ion-android-add' => array('group' => 'all'),
					'ion-android-add-circle' => array('group' => 'all'),
					'ion-android-alarm-clock' => array('group' => 'all'),
					'ion-android-alert' => array('group' => 'all'),
					'ion-android-apps' => array('group' => 'all'),
					'ion-android-archive' => array('group' => 'all'),
					'ion-android-arrow-back' => array('group' => 'all'),
					'ion-android-arrow-down' => array('group' => 'all'),
					'ion-android-arrow-dropdown' => array('group' => 'all'),
					'ion-android-arrow-dropdown-circle' => array('group' => 'all'),
					'ion-android-arrow-dropleft' => array('group' => 'all'),
					'ion-android-arrow-dropleft-circle' => array('group' => 'all'),
					'ion-android-arrow-dropright' => array('group' => 'all'),
					'ion-android-arrow-dropright-circle' => array('group' => 'all'),
					'ion-android-arrow-dropup' => array('group' => 'all'),
					'ion-android-arrow-dropup-circle' => array('group' => 'all'),
					'ion-android-arrow-forward' => array('group' => 'all'),
					'ion-android-arrow-up' => array('group' => 'all'),
					'ion-android-attach' => array('group' => 'all'),
					'ion-android-bar' => array('group' => 'all'),
					'ion-android-bicycle' => array('group' => 'all'),
					'ion-android-boat' => array('group' => 'all'),
					'ion-android-bookmark' => array('group' => 'all'),
					'ion-android-bulb' => array('group' => 'all'),
					'ion-android-bus' => array('group' => 'all'),
					'ion-android-calendar' => array('group' => 'all'),
					'ion-android-call' => array('group' => 'all'),
					'ion-android-camera' => array('group' => 'all'),
					'ion-android-cancel' => array('group' => 'all'),
					'ion-android-car' => array('group' => 'all'),
					'ion-android-cart' => array('group' => 'all'),
					'ion-android-chat' => array('group' => 'all'),
					'ion-android-checkbox' => array('group' => 'all'),
					'ion-android-checkbox-blank' => array('group' => 'all'),
					'ion-android-checkbox-outline' => array('group' => 'all'),
					'ion-android-checkbox-outline-blank' => array('group' => 'all'),
					'ion-android-checkmark-circle' => array('group' => 'all'),
					'ion-android-clipboard' => array('group' => 'all'),
					'ion-android-close' => array('group' => 'all'),
					'ion-android-cloud' => array('group' => 'all'),
					'ion-android-cloud-circle' => array('group' => 'all'),
					'ion-android-cloud-done' => array('group' => 'all'),
					'ion-android-cloud-outline' => array('group' => 'all'),
					'ion-android-color-palette' => array('group' => 'all'),
					'ion-android-compass' => array('group' => 'all'),
					'ion-android-contact' => array('group' => 'all'),
					'ion-android-contacts' => array('group' => 'all'),
					'ion-android-contract' => array('group' => 'all'),
					'ion-android-create' => array('group' => 'all'),
					'ion-android-delete' => array('group' => 'all'),
					'ion-android-desktop' => array('group' => 'all'),
					'ion-android-document' => array('group' => 'all'),
					'ion-android-done' => array('group' => 'all'),
					'ion-android-done-all' => array('group' => 'all'),
					'ion-android-download' => array('group' => 'all'),
					'ion-android-drafts' => array('group' => 'all'),
					'ion-android-exit' => array('group' => 'all'),
					'ion-android-expand' => array('group' => 'all'),
					'ion-android-favorite' => array('group' => 'all'),
					'ion-android-favorite-outline' => array('group' => 'all'),
					'ion-android-film' => array('group' => 'all'),
					'ion-android-folder' => array('group' => 'all'),
					'ion-android-folder-open' => array('group' => 'all'),
					'ion-android-funnel' => array('group' => 'all'),
					'ion-android-globe' => array('group' => 'all'),
					'ion-android-hand' => array('group' => 'all'),
					'ion-android-hangout' => array('group' => 'all'),
					'ion-android-happy' => array('group' => 'all'),
					'ion-android-home' => array('group' => 'all'),
					'ion-android-image' => array('group' => 'all'),
					'ion-android-laptop' => array('group' => 'all'),
					'ion-android-list' => array('group' => 'all'),
					'ion-android-locate' => array('group' => 'all'),
					'ion-android-lock' => array('group' => 'all'),
					'ion-android-mail' => array('group' => 'all'),
					'ion-android-map' => array('group' => 'all'),
					'ion-android-menu' => array('group' => 'all'),
					'ion-android-microphone' => array('group' => 'all'),
					'ion-android-microphone-off' => array('group' => 'all'),
					'ion-android-more-horizontal' => array('group' => 'all'),
					'ion-android-more-vertical' => array('group' => 'all'),
					'ion-android-navigate' => array('group' => 'all'),
					'ion-android-notifications' => array('group' => 'all'),
					'ion-android-notifications-none' => array('group' => 'all'),
					'ion-android-notifications-off' => array('group' => 'all'),
					'ion-android-open' => array('group' => 'all'),
					'ion-android-options' => array('group' => 'all'),
					'ion-android-people' => array('group' => 'all'),
					'ion-android-person' => array('group' => 'all'),
					'ion-android-person-add' => array('group' => 'all'),
					'ion-android-phone-landscape' => array('group' => 'all'),
					'ion-android-phone-portrait' => array('group' => 'all'),
					'ion-android-pin' => array('group' => 'all'),
					'ion-android-plane' => array('group' => 'all'),
					'ion-android-playstore' => array('group' => 'all'),
					'ion-android-print' => array('group' => 'all'),
					'ion-android-radio-button-off' => array('group' => 'all'),
					'ion-android-radio-button-on' => array('group' => 'all'),
					'ion-android-refresh' => array('group' => 'all'),
					'ion-android-remove' => array('group' => 'all'),
					'ion-android-remove-circle' => array('group' => 'all'),
					'ion-android-restaurant' => array('group' => 'all'),
					'ion-android-sad' => array('group' => 'all'),
					'ion-android-search' => array('group' => 'all'),
					'ion-android-send' => array('group' => 'all'),
					'ion-android-settings' => array('group' => 'all'),
					'ion-android-share' => array('group' => 'all'),
					'ion-android-share-alt' => array('group' => 'all'),
					'ion-android-star' => array('group' => 'all'),
					'ion-android-star-half' => array('group' => 'all'),
					'ion-android-star-outline' => array('group' => 'all'),
					'ion-android-stopwatch' => array('group' => 'all'),
					'ion-android-subway' => array('group' => 'all'),
					'ion-android-sunny' => array('group' => 'all'),
					'ion-android-sync' => array('group' => 'all'),
					'ion-android-textsms' => array('group' => 'all'),
					'ion-android-time' => array('group' => 'all'),
					'ion-android-train' => array('group' => 'all'),
					'ion-android-unlock' => array('group' => 'all'),
					'ion-android-upload' => array('group' => 'all'),
					'ion-android-volume-down' => array('group' => 'all'),
					'ion-android-volume-mute' => array('group' => 'all'),
					'ion-android-volume-off' => array('group' => 'all'),
					'ion-android-volume-up' => array('group' => 'all'),
					'ion-android-walk' => array('group' => 'all'),
					'ion-android-warning' => array('group' => 'all'),
					'ion-android-watch' => array('group' => 'all'),
					'ion-android-wifi' => array('group' => 'all'),
					'ion-aperture' => array('group' => 'all'),
					'ion-archive' => array('group' => 'all'),
					'ion-arrow-down-a' => array('group' => 'all'),
					'ion-arrow-down-b' => array('group' => 'all'),
					'ion-arrow-down-c' => array('group' => 'all'),
					'ion-arrow-expand' => array('group' => 'all'),
					'ion-arrow-graph-down-left' => array('group' => 'all'),
					'ion-arrow-graph-down-right' => array('group' => 'all'),
					'ion-arrow-graph-up-left' => array('group' => 'all'),
					'ion-arrow-graph-up-right' => array('group' => 'all'),
					'ion-arrow-left-a' => array('group' => 'all'),
					'ion-arrow-left-b' => array('group' => 'all'),
					'ion-arrow-left-c' => array('group' => 'all'),
					'ion-arrow-move' => array('group' => 'all'),
					'ion-arrow-resize' => array('group' => 'all'),
					'ion-arrow-return-left' => array('group' => 'all'),
					'ion-arrow-return-right' => array('group' => 'all'),
					'ion-arrow-right-a' => array('group' => 'all'),
					'ion-arrow-right-b' => array('group' => 'all'),
					'ion-arrow-right-c' => array('group' => 'all'),
					'ion-arrow-shrink' => array('group' => 'all'),
					'ion-arrow-swap' => array('group' => 'all'),
					'ion-arrow-up-a' => array('group' => 'all'),
					'ion-arrow-up-b' => array('group' => 'all'),
					'ion-arrow-up-c' => array('group' => 'all'),
					'ion-asterisk' => array('group' => 'all'),
					'ion-at' => array('group' => 'all'),
					'ion-backspace' => array('group' => 'all'),
					'ion-backspace-outline' => array('group' => 'all'),
					'ion-bag' => array('group' => 'all'),
					'ion-battery-charging' => array('group' => 'all'),
					'ion-battery-empty' => array('group' => 'all'),
					'ion-battery-full' => array('group' => 'all'),
					'ion-battery-half' => array('group' => 'all'),
					'ion-battery-low' => array('group' => 'all'),
					'ion-beaker' => array('group' => 'all'),
					'ion-beer' => array('group' => 'all'),
					'ion-bluetooth' => array('group' => 'all'),
					'ion-bonfire' => array('group' => 'all'),
					'ion-bookmark' => array('group' => 'all'),
					'ion-bowtie' => array('group' => 'all'),
					'ion-briefcase' => array('group' => 'all'),
					'ion-bug' => array('group' => 'all'),
					'ion-calculator' => array('group' => 'all'),
					'ion-calendar' => array('group' => 'all'),
					'ion-camera' => array('group' => 'all'),
					'ion-card' => array('group' => 'all'),
					'ion-cash' => array('group' => 'all'),
					'ion-chatbox' => array('group' => 'all'),
					'ion-chatbox-working' => array('group' => 'all'),
					'ion-chatboxes' => array('group' => 'all'),
					'ion-chatbubble' => array('group' => 'all'),
					'ion-chatbubble-working' => array('group' => 'all'),
					'ion-chatbubbles' => array('group' => 'all'),
					'ion-checkmark' => array('group' => 'all'),
					'ion-checkmark-circled' => array('group' => 'all'),
					'ion-checkmark-round' => array('group' => 'all'),
					'ion-chevron-down' => array('group' => 'all'),
					'ion-chevron-left' => array('group' => 'all'),
					'ion-chevron-right' => array('group' => 'all'),
					'ion-chevron-up' => array('group' => 'all'),
					'ion-clipboard' => array('group' => 'all'),
					'ion-clock' => array('group' => 'all'),
					'ion-close' => array('group' => 'all'),
					'ion-close-circled' => array('group' => 'all'),
					'ion-close-round' => array('group' => 'all'),
					'ion-closed-captioning' => array('group' => 'all'),
					'ion-cloud' => array('group' => 'all'),
					'ion-code' => array('group' => 'all'),
					'ion-code-download' => array('group' => 'all'),
					'ion-code-working' => array('group' => 'all'),
					'ion-coffee' => array('group' => 'all'),
					'ion-compass' => array('group' => 'all'),
					'ion-compose' => array('group' => 'all'),
					'ion-connection-bars' => array('group' => 'all'),
					'ion-contrast' => array('group' => 'all'),
					'ion-crop' => array('group' => 'all'),
					'ion-cube' => array('group' => 'all'),
					'ion-disc' => array('group' => 'all'),
					'ion-document' => array('group' => 'all'),
					'ion-document-text' => array('group' => 'all'),
					'ion-drag' => array('group' => 'all'),
					'ion-earth' => array('group' => 'all'),
					'ion-easel' => array('group' => 'all'),
					'ion-edit' => array('group' => 'all'),
					'ion-egg' => array('group' => 'all'),
					'ion-eject' => array('group' => 'all'),
					'ion-email' => array('group' => 'all'),
					'ion-email-unread' => array('group' => 'all'),
					'ion-erlenmeyer-flask' => array('group' => 'all'),
					'ion-erlenmeyer-flask-bubbles' => array('group' => 'all'),
					'ion-eye' => array('group' => 'all'),
					'ion-eye-disabled' => array('group' => 'all'),
					'ion-female' => array('group' => 'all'),
					'ion-filing' => array('group' => 'all'),
					'ion-film-marker' => array('group' => 'all'),
					'ion-fireball' => array('group' => 'all'),
					'ion-flag' => array('group' => 'all'),
					'ion-flame' => array('group' => 'all'),
					'ion-flash' => array('group' => 'all'),
					'ion-flash-off' => array('group' => 'all'),
					'ion-folder' => array('group' => 'all'),
					'ion-fork' => array('group' => 'all'),
					'ion-fork-repo' => array('group' => 'all'),
					'ion-forward' => array('group' => 'all'),
					'ion-funnel' => array('group' => 'all'),
					'ion-gear-a' => array('group' => 'all'),
					'ion-gear-b' => array('group' => 'all'),
					'ion-grid' => array('group' => 'all'),
					'ion-hammer' => array('group' => 'all'),
					'ion-happy' => array('group' => 'all'),
					'ion-happy-outline' => array('group' => 'all'),
					'ion-headphone' => array('group' => 'all'),
					'ion-heart' => array('group' => 'all'),
					'ion-heart-broken' => array('group' => 'all'),
					'ion-help' => array('group' => 'all'),
					'ion-help-buoy' => array('group' => 'all'),
					'ion-help-circled' => array('group' => 'all'),
					'ion-home' => array('group' => 'all'),
					'ion-icecream' => array('group' => 'all'),
					'ion-image' => array('group' => 'all'),
					'ion-images' => array('group' => 'all'),
					'ion-information' => array('group' => 'all'),
					'ion-information-circled' => array('group' => 'all'),
					'ion-ionic' => array('group' => 'all'),
					'ion-ios-alarm' => array('group' => 'all'),
					'ion-ios-alarm-outline' => array('group' => 'all'),
					'ion-ios-albums' => array('group' => 'all'),
					'ion-ios-albums-outline' => array('group' => 'all'),
					'ion-ios-americanfootball' => array('group' => 'all'),
					'ion-ios-americanfootball-outline' => array('group' => 'all'),
					'ion-ios-analytics' => array('group' => 'all'),
					'ion-ios-analytics-outline' => array('group' => 'all'),
					'ion-ios-arrow-back' => array('group' => 'all'),
					'ion-ios-arrow-down' => array('group' => 'all'),
					'ion-ios-arrow-forward' => array('group' => 'all'),
					'ion-ios-arrow-left' => array('group' => 'all'),
					'ion-ios-arrow-right' => array('group' => 'all'),
					'ion-ios-arrow-thin-down' => array('group' => 'all'),
					'ion-ios-arrow-thin-left' => array('group' => 'all'),
					'ion-ios-arrow-thin-right' => array('group' => 'all'),
					'ion-ios-arrow-thin-up' => array('group' => 'all'),
					'ion-ios-arrow-up' => array('group' => 'all'),
					'ion-ios-at' => array('group' => 'all'),
					'ion-ios-at-outline' => array('group' => 'all'),
					'ion-ios-barcode' => array('group' => 'all'),
					'ion-ios-barcode-outline' => array('group' => 'all'),
					'ion-ios-baseball' => array('group' => 'all'),
					'ion-ios-baseball-outline' => array('group' => 'all'),
					'ion-ios-basketball' => array('group' => 'all'),
					'ion-ios-basketball-outline' => array('group' => 'all'),
					'ion-ios-bell' => array('group' => 'all'),
					'ion-ios-bell-outline' => array('group' => 'all'),
					'ion-ios-body' => array('group' => 'all'),
					'ion-ios-body-outline' => array('group' => 'all'),
					'ion-ios-bolt' => array('group' => 'all'),
					'ion-ios-bolt-outline' => array('group' => 'all'),
					'ion-ios-book' => array('group' => 'all'),
					'ion-ios-book-outline' => array('group' => 'all'),
					'ion-ios-bookmarks' => array('group' => 'all'),
					'ion-ios-bookmarks-outline' => array('group' => 'all'),
					'ion-ios-box' => array('group' => 'all'),
					'ion-ios-box-outline' => array('group' => 'all'),
					'ion-ios-briefcase' => array('group' => 'all'),
					'ion-ios-briefcase-outline' => array('group' => 'all'),
					'ion-ios-browsers' => array('group' => 'all'),
					'ion-ios-browsers-outline' => array('group' => 'all'),
					'ion-ios-calculator' => array('group' => 'all'),
					'ion-ios-calculator-outline' => array('group' => 'all'),
					'ion-ios-calendar' => array('group' => 'all'),
					'ion-ios-calendar-outline' => array('group' => 'all'),
					'ion-ios-camera' => array('group' => 'all'),
					'ion-ios-camera-outline' => array('group' => 'all'),
					'ion-ios-cart' => array('group' => 'all'),
					'ion-ios-cart-outline' => array('group' => 'all'),
					'ion-ios-chatboxes' => array('group' => 'all'),
					'ion-ios-chatboxes-outline' => array('group' => 'all'),
					'ion-ios-chatbubble' => array('group' => 'all'),
					'ion-ios-chatbubble-outline' => array('group' => 'all'),
					'ion-ios-checkmark' => array('group' => 'all'),
					'ion-ios-checkmark-empty' => array('group' => 'all'),
					'ion-ios-checkmark-outline' => array('group' => 'all'),
					'ion-ios-circle-filled' => array('group' => 'all'),
					'ion-ios-circle-outline' => array('group' => 'all'),
					'ion-ios-clock' => array('group' => 'all'),
					'ion-ios-clock-outline' => array('group' => 'all'),
					'ion-ios-close' => array('group' => 'all'),
					'ion-ios-close-empty' => array('group' => 'all'),
					'ion-ios-close-outline' => array('group' => 'all'),
					'ion-ios-cloud' => array('group' => 'all'),
					'ion-ios-cloud-download' => array('group' => 'all'),
					'ion-ios-cloud-download-outline' => array('group' => 'all'),
					'ion-ios-cloud-outline' => array('group' => 'all'),
					'ion-ios-cloud-upload' => array('group' => 'all'),
					'ion-ios-cloud-upload-outline' => array('group' => 'all'),
					'ion-ios-cloudy' => array('group' => 'all'),
					'ion-ios-cloudy-night' => array('group' => 'all'),
					'ion-ios-cloudy-night-outline' => array('group' => 'all'),
					'ion-ios-cloudy-outline' => array('group' => 'all'),
					'ion-ios-cog' => array('group' => 'all'),
					'ion-ios-cog-outline' => array('group' => 'all'),
					'ion-ios-color-filter' => array('group' => 'all'),
					'ion-ios-color-filter-outline' => array('group' => 'all'),
					'ion-ios-color-wand' => array('group' => 'all'),
					'ion-ios-color-wand-outline' => array('group' => 'all'),
					'ion-ios-compose' => array('group' => 'all'),
					'ion-ios-compose-outline' => array('group' => 'all'),
					'ion-ios-contact' => array('group' => 'all'),
					'ion-ios-contact-outline' => array('group' => 'all'),
					'ion-ios-copy' => array('group' => 'all'),
					'ion-ios-copy-outline' => array('group' => 'all'),
					'ion-ios-crop' => array('group' => 'all'),
					'ion-ios-crop-strong' => array('group' => 'all'),
					'ion-ios-download' => array('group' => 'all'),
					'ion-ios-download-outline' => array('group' => 'all'),
					'ion-ios-drag' => array('group' => 'all'),
					'ion-ios-email' => array('group' => 'all'),
					'ion-ios-email-outline' => array('group' => 'all'),
					'ion-ios-eye' => array('group' => 'all'),
					'ion-ios-eye-outline' => array('group' => 'all'),
					'ion-ios-fastforward' => array('group' => 'all'),
					'ion-ios-fastforward-outline' => array('group' => 'all'),
					'ion-ios-filing' => array('group' => 'all'),
					'ion-ios-filing-outline' => array('group' => 'all'),
					'ion-ios-film' => array('group' => 'all'),
					'ion-ios-film-outline' => array('group' => 'all'),
					'ion-ios-flag' => array('group' => 'all'),
					'ion-ios-flag-outline' => array('group' => 'all'),
					'ion-ios-flame' => array('group' => 'all'),
					'ion-ios-flame-outline' => array('group' => 'all'),
					'ion-ios-flask' => array('group' => 'all'),
					'ion-ios-flask-outline' => array('group' => 'all'),
					'ion-ios-flower' => array('group' => 'all'),
					'ion-ios-flower-outline' => array('group' => 'all'),
					'ion-ios-folder' => array('group' => 'all'),
					'ion-ios-folder-outline' => array('group' => 'all'),
					'ion-ios-football' => array('group' => 'all'),
					'ion-ios-football-outline' => array('group' => 'all'),
					'ion-ios-game-controller-a' => array('group' => 'all'),
					'ion-ios-game-controller-a-outline' => array('group' => 'all'),
					'ion-ios-game-controller-b' => array('group' => 'all'),
					'ion-ios-game-controller-b-outline' => array('group' => 'all'),
					'ion-ios-gear' => array('group' => 'all'),
					'ion-ios-gear-outline' => array('group' => 'all'),
					'ion-ios-glasses' => array('group' => 'all'),
					'ion-ios-glasses-outline' => array('group' => 'all'),
					'ion-ios-grid-view' => array('group' => 'all'),
					'ion-ios-grid-view-outline' => array('group' => 'all'),
					'ion-ios-heart' => array('group' => 'all'),
					'ion-ios-heart-outline' => array('group' => 'all'),
					'ion-ios-help' => array('group' => 'all'),
					'ion-ios-help-empty' => array('group' => 'all'),
					'ion-ios-help-outline' => array('group' => 'all'),
					'ion-ios-home' => array('group' => 'all'),
					'ion-ios-home-outline' => array('group' => 'all'),
					'ion-ios-infinite' => array('group' => 'all'),
					'ion-ios-infinite-outline' => array('group' => 'all'),
					'ion-ios-information' => array('group' => 'all'),
					'ion-ios-information-empty' => array('group' => 'all'),
					'ion-ios-information-outline' => array('group' => 'all'),
					'ion-ios-ionic-outline' => array('group' => 'all'),
					'ion-ios-keypad' => array('group' => 'all'),
					'ion-ios-keypad-outline' => array('group' => 'all'),
					'ion-ios-lightbulb' => array('group' => 'all'),
					'ion-ios-lightbulb-outline' => array('group' => 'all'),
					'ion-ios-list' => array('group' => 'all'),
					'ion-ios-list-outline' => array('group' => 'all'),
					'ion-ios-location' => array('group' => 'all'),
					'ion-ios-location-outline' => array('group' => 'all'),
					'ion-ios-locked' => array('group' => 'all'),
					'ion-ios-locked-outline' => array('group' => 'all'),
					'ion-ios-loop' => array('group' => 'all'),
					'ion-ios-loop-strong' => array('group' => 'all'),
					'ion-ios-medical' => array('group' => 'all'),
					'ion-ios-medical-outline' => array('group' => 'all'),
					'ion-ios-medkit' => array('group' => 'all'),
					'ion-ios-medkit-outline' => array('group' => 'all'),
					'ion-ios-mic' => array('group' => 'all'),
					'ion-ios-mic-off' => array('group' => 'all'),
					'ion-ios-mic-outline' => array('group' => 'all'),
					'ion-ios-minus' => array('group' => 'all'),
					'ion-ios-minus-empty' => array('group' => 'all'),
					'ion-ios-minus-outline' => array('group' => 'all'),
					'ion-ios-monitor' => array('group' => 'all'),
					'ion-ios-monitor-outline' => array('group' => 'all'),
					'ion-ios-moon' => array('group' => 'all'),
					'ion-ios-moon-outline' => array('group' => 'all'),
					'ion-ios-more' => array('group' => 'all'),
					'ion-ios-more-outline' => array('group' => 'all'),
					'ion-ios-musical-note' => array('group' => 'all'),
					'ion-ios-musical-notes' => array('group' => 'all'),
					'ion-ios-navigate' => array('group' => 'all'),
					'ion-ios-navigate-outline' => array('group' => 'all'),
					'ion-ios-nutrition' => array('group' => 'all'),
					'ion-ios-nutrition-outline' => array('group' => 'all'),
					'ion-ios-paper' => array('group' => 'all'),
					'ion-ios-paper-outline' => array('group' => 'all'),
					'ion-ios-paperplane' => array('group' => 'all'),
					'ion-ios-paperplane-outline' => array('group' => 'all'),
					'ion-ios-partlysunny' => array('group' => 'all'),
					'ion-ios-partlysunny-outline' => array('group' => 'all'),
					'ion-ios-pause' => array('group' => 'all'),
					'ion-ios-pause-outline' => array('group' => 'all'),
					'ion-ios-paw' => array('group' => 'all'),
					'ion-ios-paw-outline' => array('group' => 'all'),
					'ion-ios-people' => array('group' => 'all'),
					'ion-ios-people-outline' => array('group' => 'all'),
					'ion-ios-person' => array('group' => 'all'),
					'ion-ios-person-outline' => array('group' => 'all'),
					'ion-ios-personadd' => array('group' => 'all'),
					'ion-ios-personadd-outline' => array('group' => 'all'),
					'ion-ios-photos' => array('group' => 'all'),
					'ion-ios-photos-outline' => array('group' => 'all'),
					'ion-ios-pie' => array('group' => 'all'),
					'ion-ios-pie-outline' => array('group' => 'all'),
					'ion-ios-pint' => array('group' => 'all'),
					'ion-ios-pint-outline' => array('group' => 'all'),
					'ion-ios-play' => array('group' => 'all'),
					'ion-ios-play-outline' => array('group' => 'all'),
					'ion-ios-plus' => array('group' => 'all'),
					'ion-ios-plus-empty' => array('group' => 'all'),
					'ion-ios-plus-outline' => array('group' => 'all'),
					'ion-ios-pricetag' => array('group' => 'all'),
					'ion-ios-pricetag-outline' => array('group' => 'all'),
					'ion-ios-pricetags' => array('group' => 'all'),
					'ion-ios-pricetags-outline' => array('group' => 'all'),
					'ion-ios-printer' => array('group' => 'all'),
					'ion-ios-printer-outline' => array('group' => 'all'),
					'ion-ios-pulse' => array('group' => 'all'),
					'ion-ios-pulse-strong' => array('group' => 'all'),
					'ion-ios-rainy' => array('group' => 'all'),
					'ion-ios-rainy-outline' => array('group' => 'all'),
					'ion-ios-recording' => array('group' => 'all'),
					'ion-ios-recording-outline' => array('group' => 'all'),
					'ion-ios-redo' => array('group' => 'all'),
					'ion-ios-redo-outline' => array('group' => 'all'),
					'ion-ios-refresh' => array('group' => 'all'),
					'ion-ios-refresh-empty' => array('group' => 'all'),
					'ion-ios-refresh-outline' => array('group' => 'all'),
					'ion-ios-reload' => array('group' => 'all'),
					'ion-ios-reverse-camera' => array('group' => 'all'),
					'ion-ios-reverse-camera-outline' => array('group' => 'all'),
					'ion-ios-rewind' => array('group' => 'all'),
					'ion-ios-rewind-outline' => array('group' => 'all'),
					'ion-ios-rose' => array('group' => 'all'),
					'ion-ios-rose-outline' => array('group' => 'all'),
					'ion-ios-search' => array('group' => 'all'),
					'ion-ios-search-strong' => array('group' => 'all'),
					'ion-ios-settings' => array('group' => 'all'),
					'ion-ios-settings-strong' => array('group' => 'all'),
					'ion-ios-shuffle' => array('group' => 'all'),
					'ion-ios-shuffle-strong' => array('group' => 'all'),
					'ion-ios-skipbackward' => array('group' => 'all'),
					'ion-ios-skipbackward-outline' => array('group' => 'all'),
					'ion-ios-skipforward' => array('group' => 'all'),
					'ion-ios-skipforward-outline' => array('group' => 'all'),
					'ion-ios-snowy' => array('group' => 'all'),
					'ion-ios-speedometer' => array('group' => 'all'),
					'ion-ios-speedometer-outline' => array('group' => 'all'),
					'ion-ios-star' => array('group' => 'all'),
					'ion-ios-star-half' => array('group' => 'all'),
					'ion-ios-star-outline' => array('group' => 'all'),
					'ion-ios-stopwatch' => array('group' => 'all'),
					'ion-ios-stopwatch-outline' => array('group' => 'all'),
					'ion-ios-sunny' => array('group' => 'all'),
					'ion-ios-sunny-outline' => array('group' => 'all'),
					'ion-ios-telephone' => array('group' => 'all'),
					'ion-ios-telephone-outline' => array('group' => 'all'),
					'ion-ios-tennisball' => array('group' => 'all'),
					'ion-ios-tennisball-outline' => array('group' => 'all'),
					'ion-ios-thunderstorm' => array('group' => 'all'),
					'ion-ios-thunderstorm-outline' => array('group' => 'all'),
					'ion-ios-time' => array('group' => 'all'),
					'ion-ios-time-outline' => array('group' => 'all'),
					'ion-ios-timer' => array('group' => 'all'),
					'ion-ios-timer-outline' => array('group' => 'all'),
					'ion-ios-toggle' => array('group' => 'all'),
					'ion-ios-toggle-outline' => array('group' => 'all'),
					'ion-ios-trash' => array('group' => 'all'),
					'ion-ios-trash-outline' => array('group' => 'all'),
					'ion-ios-undo' => array('group' => 'all'),
					'ion-ios-undo-outline' => array('group' => 'all'),
					'ion-ios-unlocked' => array('group' => 'all'),
					'ion-ios-unlocked-outline' => array('group' => 'all'),
					'ion-ios-upload' => array('group' => 'all'),
					'ion-ios-upload-outline' => array('group' => 'all'),
					'ion-ios-videocam' => array('group' => 'all'),
					'ion-ios-videocam-outline' => array('group' => 'all'),
					'ion-ios-volume-high' => array('group' => 'all'),
					'ion-ios-volume-low' => array('group' => 'all'),
					'ion-ios-wineglass' => array('group' => 'all'),
					'ion-ios-wineglass-outline' => array('group' => 'all'),
					'ion-ios-world' => array('group' => 'all'),
					'ion-ios-world-outline' => array('group' => 'all'),
					'ion-ipad' => array('group' => 'all'),
					'ion-iphone' => array('group' => 'all'),
					'ion-ipod' => array('group' => 'all'),
					'ion-jet' => array('group' => 'all'),
					'ion-key' => array('group' => 'all'),
					'ion-knife' => array('group' => 'all'),
					'ion-laptop' => array('group' => 'all'),
					'ion-leaf' => array('group' => 'all'),
					'ion-levels' => array('group' => 'all'),
					'ion-lightbulb' => array('group' => 'all'),
					'ion-link' => array('group' => 'all'),
					'ion-load-a' => array('group' => 'all'),
					'ion-load-b' => array('group' => 'all'),
					'ion-load-c' => array('group' => 'all'),
					'ion-load-d' => array('group' => 'all'),
					'ion-location' => array('group' => 'all'),
					'ion-lock-combination' => array('group' => 'all'),
					'ion-locked' => array('group' => 'all'),
					'ion-log-in' => array('group' => 'all'),
					'ion-log-out' => array('group' => 'all'),
					'ion-loop' => array('group' => 'all'),
					'ion-magnet' => array('group' => 'all'),
					'ion-male' => array('group' => 'all'),
					'ion-man' => array('group' => 'all'),
					'ion-map' => array('group' => 'all'),
					'ion-medkit' => array('group' => 'all'),
					'ion-merge' => array('group' => 'all'),
					'ion-mic-a' => array('group' => 'all'),
					'ion-mic-b' => array('group' => 'all'),
					'ion-mic-c' => array('group' => 'all'),
					'ion-minus' => array('group' => 'all'),
					'ion-minus-circled' => array('group' => 'all'),
					'ion-minus-round' => array('group' => 'all'),
					'ion-model-s' => array('group' => 'all'),
					'ion-monitor' => array('group' => 'all'),
					'ion-more' => array('group' => 'all'),
					'ion-mouse' => array('group' => 'all'),
					'ion-music-note' => array('group' => 'all'),
					'ion-navicon' => array('group' => 'all'),
					'ion-navicon-round' => array('group' => 'all'),
					'ion-navigate' => array('group' => 'all'),
					'ion-network' => array('group' => 'all'),
					'ion-no-smoking' => array('group' => 'all'),
					'ion-nuclear' => array('group' => 'all'),
					'ion-outlet' => array('group' => 'all'),
					'ion-paintbrush' => array('group' => 'all'),
					'ion-paintbucket' => array('group' => 'all'),
					'ion-paper-airplane' => array('group' => 'all'),
					'ion-paperclip' => array('group' => 'all'),
					'ion-pause' => array('group' => 'all'),
					'ion-person' => array('group' => 'all'),
					'ion-person-add' => array('group' => 'all'),
					'ion-person-stalker' => array('group' => 'all'),
					'ion-pie-graph' => array('group' => 'all'),
					'ion-pin' => array('group' => 'all'),
					'ion-pinpoint' => array('group' => 'all'),
					'ion-pizza' => array('group' => 'all'),
					'ion-plane' => array('group' => 'all'),
					'ion-planet' => array('group' => 'all'),
					'ion-play' => array('group' => 'all'),
					'ion-playstation' => array('group' => 'all'),
					'ion-plus' => array('group' => 'all'),
					'ion-plus-circled' => array('group' => 'all'),
					'ion-plus-round' => array('group' => 'all'),
					'ion-podium' => array('group' => 'all'),
					'ion-pound' => array('group' => 'all'),
					'ion-power' => array('group' => 'all'),
					'ion-pricetag' => array('group' => 'all'),
					'ion-pricetags' => array('group' => 'all'),
					'ion-printer' => array('group' => 'all'),
					'ion-pull-request' => array('group' => 'all'),
					'ion-qr-scanner' => array('group' => 'all'),
					'ion-quote' => array('group' => 'all'),
					'ion-radio-waves' => array('group' => 'all'),
					'ion-record' => array('group' => 'all'),
					'ion-refresh' => array('group' => 'all'),
					'ion-reply' => array('group' => 'all'),
					'ion-reply-all' => array('group' => 'all'),
					'ion-ribbon-a' => array('group' => 'all'),
					'ion-ribbon-b' => array('group' => 'all'),
					'ion-sad' => array('group' => 'all'),
					'ion-sad-outline' => array('group' => 'all'),
					'ion-scissors' => array('group' => 'all'),
					'ion-search' => array('group' => 'all'),
					'ion-settings' => array('group' => 'all'),
					'ion-share' => array('group' => 'all'),
					'ion-shuffle' => array('group' => 'all'),
					'ion-skip-backward' => array('group' => 'all'),
					'ion-skip-forward' => array('group' => 'all'),
					'ion-social-android' => array('group' => 'all'),
					'ion-social-android-outline' => array('group' => 'all'),
					'ion-social-angular' => array('group' => 'all'),
					'ion-social-angular-outline' => array('group' => 'all'),
					'ion-social-apple' => array('group' => 'all'),
					'ion-social-apple-outline' => array('group' => 'all'),
					'ion-social-bitcoin' => array('group' => 'all'),
					'ion-social-bitcoin-outline' => array('group' => 'all'),
					'ion-social-buffer' => array('group' => 'all'),
					'ion-social-buffer-outline' => array('group' => 'all'),
					'ion-social-chrome' => array('group' => 'all'),
					'ion-social-chrome-outline' => array('group' => 'all'),
					'ion-social-codepen' => array('group' => 'all'),
					'ion-social-codepen-outline' => array('group' => 'all'),
					'ion-social-css3' => array('group' => 'all'),
					'ion-social-css3-outline' => array('group' => 'all'),
					'ion-social-designernews' => array('group' => 'all'),
					'ion-social-designernews-outline' => array('group' => 'all'),
					'ion-social-dribbble' => array('group' => 'all'),
					'ion-social-dribbble-outline' => array('group' => 'all'),
					'ion-social-dropbox' => array('group' => 'all'),
					'ion-social-dropbox-outline' => array('group' => 'all'),
					'ion-social-euro' => array('group' => 'all'),
					'ion-social-euro-outline' => array('group' => 'all'),
					'ion-social-facebook' => array('group' => 'all'),
					'ion-social-facebook-outline' => array('group' => 'all'),
					'ion-social-foursquare' => array('group' => 'all'),
					'ion-social-foursquare-outline' => array('group' => 'all'),
					'ion-social-freebsd-devil' => array('group' => 'all'),
					'ion-social-github' => array('group' => 'all'),
					'ion-social-github-outline' => array('group' => 'all'),
					'ion-social-google' => array('group' => 'all'),
					'ion-social-google-outline' => array('group' => 'all'),
					'ion-social-googleplus' => array('group' => 'all'),
					'ion-social-googleplus-outline' => array('group' => 'all'),
					'ion-social-hackernews' => array('group' => 'all'),
					'ion-social-hackernews-outline' => array('group' => 'all'),
					'ion-social-html5' => array('group' => 'all'),
					'ion-social-html5-outline' => array('group' => 'all'),
					'ion-social-instagram' => array('group' => 'all'),
					'ion-social-instagram-outline' => array('group' => 'all'),
					'ion-social-javascript' => array('group' => 'all'),
					'ion-social-javascript-outline' => array('group' => 'all'),
					'ion-social-linkedin' => array('group' => 'all'),
					'ion-social-linkedin-outline' => array('group' => 'all'),
					'ion-social-markdown' => array('group' => 'all'),
					'ion-social-nodejs' => array('group' => 'all'),
					'ion-social-octocat' => array('group' => 'all'),
					'ion-social-pinterest' => array('group' => 'all'),
					'ion-social-pinterest-outline' => array('group' => 'all'),
					'ion-social-python' => array('group' => 'all'),
					'ion-social-reddit' => array('group' => 'all'),
					'ion-social-reddit-outline' => array('group' => 'all'),
					'ion-social-rss' => array('group' => 'all'),
					'ion-social-rss-outline' => array('group' => 'all'),
					'ion-social-sass' => array('group' => 'all'),
					'ion-social-skype' => array('group' => 'all'),
					'ion-social-skype-outline' => array('group' => 'all'),
					'ion-social-snapchat' => array('group' => 'all'),
					'ion-social-snapchat-outline' => array('group' => 'all'),
					'ion-social-tumblr' => array('group' => 'all'),
					'ion-social-tumblr-outline' => array('group' => 'all'),
					'ion-social-tux' => array('group' => 'all'),
					'ion-social-twitch' => array('group' => 'all'),
					'ion-social-twitch-outline' => array('group' => 'all'),
					'ion-social-twitter' => array('group' => 'all'),
					'ion-social-twitter-outline' => array('group' => 'all'),
					'ion-social-usd' => array('group' => 'all'),
					'ion-social-usd-outline' => array('group' => 'all'),
					'ion-social-vimeo' => array('group' => 'all'),
					'ion-social-vimeo-outline' => array('group' => 'all'),
					'ion-social-whatsapp' => array('group' => 'all'),
					'ion-social-whatsapp-outline' => array('group' => 'all'),
					'ion-social-windows' => array('group' => 'all'),
					'ion-social-windows-outline' => array('group' => 'all'),
					'ion-social-wordpress' => array('group' => 'all'),
					'ion-social-wordpress-outline' => array('group' => 'all'),
					'ion-social-yahoo' => array('group' => 'all'),
					'ion-social-yahoo-outline' => array('group' => 'all'),
					'ion-social-yen' => array('group' => 'all'),
					'ion-social-yen-outline' => array('group' => 'all'),
					'ion-social-youtube' => array('group' => 'all'),
					'ion-social-youtube-outline' => array('group' => 'all'),
					'ion-soup-can' => array('group' => 'all'),
					'ion-soup-can-outline' => array('group' => 'all'),
					'ion-speakerphone' => array('group' => 'all'),
					'ion-speedometer' => array('group' => 'all'),
					'ion-spoon' => array('group' => 'all'),
					'ion-star' => array('group' => 'all'),
					'ion-stats-bars' => array('group' => 'all'),
					'ion-steam' => array('group' => 'all'),
					'ion-stop' => array('group' => 'all'),
					'ion-thermometer' => array('group' => 'all'),
					'ion-thumbsdown' => array('group' => 'all'),
					'ion-thumbsup' => array('group' => 'all'),
					'ion-toggle' => array('group' => 'all'),
					'ion-toggle-filled' => array('group' => 'all'),
					'ion-transgender' => array('group' => 'all'),
					'ion-trash-a' => array('group' => 'all'),
					'ion-trash-b' => array('group' => 'all'),
					'ion-trophy' => array('group' => 'all'),
					'ion-tshirt' => array('group' => 'all'),
					'ion-tshirt-outline' => array('group' => 'all'),
					'ion-umbrella' => array('group' => 'all'),
					'ion-university' => array('group' => 'all'),
					'ion-unlocked' => array('group' => 'all'),
					'ion-upload' => array('group' => 'all'),
					'ion-usb' => array('group' => 'all'),
					'ion-videocamera' => array('group' => 'all'),
					'ion-volume-high' => array('group' => 'all'),
					'ion-volume-low' => array('group' => 'all'),
					'ion-volume-medium' => array('group' => 'all'),
					'ion-volume-mute' => array('group' => 'all'),
					'ion-wand' => array('group' => 'all'),
					'ion-waterdrop' => array('group' => 'all'),
					'ion-wifi' => array('group' => 'all'),
					'ion-wineglass' => array('group' => 'all'),
					'ion-woman' => array('group' => 'all'),
					'ion-wrench' => array('group' => 'all'),
					'ion-xbox' => array('group' => 'all')
				),
			),
		);
	}
}
FW_Option_Type::register('FW_Option_Type_My_Icon');
